image: heptacom/heptaconnect-pipeline:php74-latest

definitions:
    services:
        mysql:
            image: mysql:5.7
            variables:
                MYSQL_DATABASE: 'pipelines'
                MYSQL_ROOT_PASSWORD: 'let_me_in'
    steps:
        -   step: &default-step
                caches:
                    - composer
                artifacts:
                    - .build/**
                    - vendor/**
                    - composer.lock

pipelines:
    default:
        -   step:
                <<: *default-step
                name: Install
                script:
                    - composer-repository
                    - make vendor
        -   step:
                <<: *default-step
                name: Unit test
                script:
                    - make test
        -   step:
                <<: *default-step
                name: Unit test coverage
                script:
                    - make coverage
        -   step:
                <<: *default-step
                name: Code style and static code analysis
                script:
                    - make cs
        -   step:
                <<: *default-step
                name: Unit test infection detection
                script:
                    - make infection
